[package]
name = "{{app-name}}"
version = "0.1.0"
edition = "2024"

[lib]
name = "tui-lib"
path = "src/lib/mod.rs"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = { version = "0.29.0",features = ["crossterm"] }
